# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  treads-frontend-dev:
    depends_on:
      treads-backend-dev:
        condition: service_started
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    image: treads-frontend:dev
    container_name: treads-frontend-dev
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/frontend.env
    develop:
      watch:
        - action: sync
          path: ./frontend/
          target: /app
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
  treads-backend-dev:
    depends_on:
      treads-database-dev:
        condition: service_healthy
    build:
      context: backend
      dockerfile: Dockerfile.dev
    image: treads-backend:dev
    container_name: treads-backend-dev
    ports:
      - "3001:3001"
    env_file:
      - ./backend/backend.env
    develop:
      watch:
        - action: sync+restart
          path: ./backend/
          target: /app
          ignore:
            - node_modules/
            - sequelize/
        - action: rebuild
          path: ./backend/package.json
  treads-database-dev:
    build:
      context: database
      dockerfile: Dockerfile.dev
    image: postgres
    volumes:
      - pg-data-dev:/var/lib/postgresql
    user: postgres
    container_name: treads-database-dev
    env_file:
      - ./database/database.env
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pg-data-dev:
