# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  frontend-dev:
    depends_on:
      database-dev:
        condition: service_healthy
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    image: treads-frontend:dev
    container_name: treads-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: package.json
  backend-dev:
    depends_on:
      database-dev:
        condition: service_healthy
    build:
      context: backend
      dockerfile: Dockerfile.dev
    image: treads-backend:dev
    container_name: treads-backend-dev
    ports:
      - "3001:3001"
    environment:
      - WATCHPACK_POLLING=true
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: package.json
  database-dev:
    build:
      context: database
      dockerfile: Dockerfile.dev
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    container_name: treads-database
    environment:
      - POSTGRES_DB=treads
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
secrets:
  db-password:
    file: database/password.txt
