# ============================================
# Development Dockerfile for Express.js
# ============================================
ARG NODE_VERSION=24.14.0-slim

FROM node:${NODE_VERSION} AS dev

WORKDIR /app

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./

RUN npm install

COPY . /app

RUN chown -R node:node /app
USER node

EXPOSE 3001

RUN npm run build

CMD ["npm", "run", "begin"]